# Calibrate files

In [39]:
import surfradpy.products.mfrsr_cosinecorrection as srfcc

# 648

In [15]:
site = 'dav'
serialno = '648'
verbose = True
# p2fld_in = f'/Volumes/grad/Inst/MFR/Campaign/frc/2025/mfrsr/648.netcdf/v0.4/''
p2fld_in = f'/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/2025/mfrsr/{serialno}.netcdf/v0.4/2025'
p2fld_out = f'/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/2025/mfrsr/{serialno}.cal/v{{version}}/'
ci = srfcc.CalibrateMFRSR(p2fld_in  = p2fld_in,
                        p2fld_out = p2fld_out,
                        date_from_name = lambda name: pd.to_datetime(name.split('_')[-1].replace('.nc', '')),
                        output_file_format = f'{{year}}/{site}_mfrsr_cosinecorrected_{{date}}.nc',
                        # glob_pattern_raw = "*.xmd",
                        start = '2025-01-01',
                        end = '2026-01-01',
                        prefix = '/Volumes',
                        # site = site,
                        # version = '0.3', # this is actually 0.3.1 but i don't want to rerun everything.
                        # path2surfrad_database = db_path,
                        reporter = None,
                        verbose = verbose,
                        )

start time: 2026-06-05 14:49:06.564675

In [16]:
ci.workplan

Get all files in /Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/2025/mfrsr/648.netcdf/v0.4/2025 with "files_between" function and start: 2025-01-01 00:00:00, end: 2026-01-01 00:00:00 and glob pattern: *.nc

,p2f_in,p2f_out
2025-09-25,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-26,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-27,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-28,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-29,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-30,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-01,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-02,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-03,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-04,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-05,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-06,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-07,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-08,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-09,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-10,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-11,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-12,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-13,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-14,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-15,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-16,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-17,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-18,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-19,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-20,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-21,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...

In [20]:
out = ci.process_row(iloc = 0, save = False)

Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

In [23]:
ci.process(raise_errors=True)

Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231020.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0648/Reported/V0648_20231012.spr

.

# 649

In [2]:
import surfradpy.products.mfrsr_cosinecorrection as srfcc

In [3]:
site = 'dav'
serialno = '649'
verbose = True
# p2fld_in = f'/Volumes/grad/Inst/MFR/Campaign/frc/2025/mfrsr/648.netcdf/v0.4/''
p2fld_in = f'/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/2025/mfrsr/{serialno}.netcdf/v0.4/2025'
p2fld_out = f'/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/2025/mfrsr/{serialno}.cal/v{{version}}/'
ci = srfcc.CalibrateMFRSR(p2fld_in  = p2fld_in,
                        p2fld_out = p2fld_out,
                        date_from_name = lambda name: pd.to_datetime(name.split('_')[-1].replace('.nc', '')),
                        output_file_format = f'{{year}}/{site}_mfrsr_cosinecorrected_{{date}}.nc',
                        # glob_pattern_raw = "*.xmd",
                        start = '2025-01-01',
                        end = '2026-01-01',
                        prefix = '/Volumes',
                        # site = site,
                        # version = '0.3', # this is actually 0.3.1 but i don't want to rerun everything.
                        # path2surfrad_database = db_path,
                        reporter = None,
                        verbose = verbose,
                        )

start time: 2026-06-05 15:39:03.495244

In [4]:
ci.workplan

Get all files in /Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/2025/mfrsr/649.netcdf/v0.4/2025 with "files_between" function and start: 2025-01-01 00:00:00, end: 2026-01-01 00:00:00 and glob pattern: *.nc

,p2f_in,p2f_out
2025-09-25,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-26,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-27,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-28,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-29,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-09-30,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-01,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-02,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-03,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-04,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-05,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-06,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-07,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-08,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-09,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-10,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-11,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-12,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-13,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-14,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-15,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-16,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-17,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-18,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-19,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-20,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...
2025-10-21,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...,/Users/htelg/nfs/grad/Inst/MFR/Campaign/frc/20...

In [6]:
out = ci.process_row(iloc = 0, save = False)

Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

In [7]:
ci.process(raise_errors=True)

Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.Using cosine calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231023.cos
Using spectral calibration file: /Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0649/Reported/V0649_20231011.spr

.